### PR TITLE
Update New Icons and Add Logo Files

### PR DESCRIPTION
**Pull request by zularizal**

### CODE REVIEW

**Comment by brminnick** [comment]
Thanks @zularizal!

Can you also add the images to the iOS app?

👇 We can put them in GeoLocatorSample.iOS > Assets.xcassets 

image

**Comment by zularizal** [comment]
Okay, I added.

**Comment by brminnick** [comment]
Awesome!

One more request, let's add round icons for Android too: https://developer.android.com/about/versions/nougat/android-7.1

Every device running Android N or later will look for a round icon, and if it doesn't find one, it squishes the square icon into a circle which looks janky:
Screenshot_1555353988

**Comment by brminnick** [comment]
To add a round icon, to the project export the same icon as a circle instead of a square, append `_Round.png` and add to each drawable folder:

Screen Shot 2019-04-15 at 11 50 14 AM

**Comment by zularizal** [comment]
Okay, I have added it. Please check

**Comment by brminnick** [comment]
Looks great! Thanks for you help!

**Comment by zularizal** [comment]
You are welcome. Glad to help

**Pull request merged**
